# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api-insumos:
    image: api-insumos
    build:
      context: .
      dockerfile: APIs/Insumos_Dockerfile
    ports:
      - 5057:5057
  api-pedidos:
    image: api-pedidos
    build:
      context: .
      dockerfile: APIs/Pedidos_Dockerfile
    ports:
      - 5058:5058
  
