ALTER TABLE Insumos
ADD Costo INT NOT NULL 
DEFAULT (0)

ALTER TABLE Insumos
ADD Precio INT NOT NULL 
DEFAULT (0)

ALTER TABLE Insumos
DROP CONSTRAINT PK_Insumos

ALTER TABLE Insumos
DROP COLUMN ID_Insumo

ALTER TABLE Insumos
ADD ID_Insumo INT IDENTITY(0,1) PRIMARY KEY NOT NULL


ALTER TABLE Productos
DROP CONSTRAINT PK_Productos

ALTER TABLE Productos
DROP COLUMN CodigoProducto

ALTER TABLE Productos
DROP COLUMN Tipo

ALTER TABLE Productos
ADD ID_Producto INT IDENTITY(0,1) PRIMARY KEY NOT NULL

ALTER TABLE Productos
ADD Precio INT NOT NULL 
DEFAULT (0)

ALTER TABLE Productos
ADD Costo INT NOT NULL 
DEFAULT (0)

CREATE TABLE InsumosDeProducto(
	ID_Producto INT FOREIGN KEY REFERENCES Productos(ID_Producto),
	ID_Insumo INT FOREIGN KEY REFERENCES Insumos(ID_Insumo),
    PRIMARY KEY (ID_Producto,ID_Insumo)
)
