# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api-pedidos:
    image: api-pedidos
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 5058:5058
